FROM ubuntu:20.04
RUN apt-get update && apt-get install -y net-tools git libevent-dev libdumbnet-dev libpcap-dev libpcre3-dev libedit-dev bison flex libtool automake zlib1g-dev make python

RUN git clone https://github.com/DataSoft/Honeyd.git
WORKDIR /Honeyd
RUN bash autogen.sh
RUN bash configure
RUN make
RUN make install
WORKDIR /
COPY scripts/start_honeypot.sh start_honeypot.sh
COPY scripts/honeypot.conf honeypot.conf
RUN apt-get install -y ethtool
CMD bash start_honeypot.sh
