FROM ubuntu:20.04
RUN apt-get update && apt-get install -y net-tools iproute2 nmap
COPY scripts/start_nmap_scanner.sh start_nmap_scanner.sh
RUN apt-get install -y ethtool
CMD bash start_nmap_scanner.sh
